export {default as Footer} from './Footer/Footer'
export {default as Header} from './Header/Header'
export {default as Img} from './LazyLoadingImg/Img'
export {default as Wrapper} from './ContentWrapper/Wrapper'
export {default as SwitchTab} from './SwitchTab/SwitchTab'